# Generated by Django 3.0 on 2019-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='value',
            field=models.BooleanField(),
        ),
    ]
